version: '3.5'

services:

  felicity_fe:
    container_name: felicity_fe
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile.webapp
    volumes:
      - ./webapp:/app
    ports:
      - "3000:3000"
    depends_on:
      - felicity_be
    networks:
      - felicitynet
    command: bash -c "pnpm dev --host --port 3000"

  felicity_be:
    container_name: felicity_be
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile.felicity
    environment:
      - POSTGRES_SERVER=felicity_db
      - POSTGRES_DB=felicity_lims
      - POSTGRES_USER=felicity
      - POSTGRES_PASSWORD=felicity
      - POSTGRES_HOST_AUTH_METHOD=trust
      - LOAD_SETUP_DATA=${LOAD_SETUP_DATA:-False}
      - SERVE_WEBAPP=${SERVE_WEBAPP:-False}
    volumes:
      - ./felicity/:/app
    ports:
      - 8000:8000
    depends_on:
      - felicity_db
    networks:
      - felicitynet
    command: bash -c "alembic upgrade head && uvicorn main:flims --host=0.0.0.0 --port=8000 --workers 1"

  felicity_db:
    container_name: felicity_db
    image: postgres:12
    restart: unless-stopped
    environment:
      - POSTGRES_DB=felicity_lims
      - POSTGRES_USER=felicity
      - POSTGRES_PASSWORD=felicity
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./postgres/init/:/docker-entrypoint-initdb.d/
      - database-data:/var/lib/postgresql/data
    ports:
      - 5434:5432
    networks:
      - felicitynet

  pgadmin:
    container_name: felicity.pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - felicitynet
    restart: unless-stopped
    depends_on:
      - felicity_db

volumes:
  db-data:
  pgadmin:

networks:
  felicitynet:
    driver: bridge
