# Split: The felicity will run independely and a reverse proxy serve the webapp's static files
version: '3.5'

services:
  # Option 1: run with nginx as a reverse proxy to serve static files
  felicity_split_nginx:
    container_name: felicity_split_nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./services/nginx:/etc/nginx/conf.d
    depends_on:
      - felicity_fe

  # Option 2: run with caddy as a reverse proxy to serve static files
  felicity_split_caddy:
    container_name: felicity_split_caddy
    image: caddy:2-alpine
    ports:
      - "$PORT:$PORT"
      - "80:80"
      - "443:443"
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - felicity_fe

  felicity_fe:
    container_name: felicity_fe
    restart: unless-stopped
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    expose:
      - "3000"
    depends_on:
      - felicity_be
    networks:
      - felicitynet
    command: bash -c "cd vite && pnpm dev --host --port 3000"

  felicity_db:
    container_name: felicity_db
    image: postgres:12
    restart: unless-stopped
    environment:
      - POSTGRES_DB=felicity_lims
      - POSTGRES_USER=felicity
      - POSTGRES_PASSWORD=felicity
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./postgres/init/:/docker-entrypoint-initdb.d/
      - database-data:/var/lib/postgresql/data
    expose:
      - "5434"
    networks:
      - felicitynet

  pgadmin:
    container_name: felicity.pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - felicitynet
    restart: unless-stopped
    depends_on:
      - felicity_db

volumes:
  db-data:
  pgadmin:
  caddy_data:
  caddy_config:

networks:
  felicitynet:
    driver: bridge
