# isort: skip_file
# skip-file
# ruff: noqa: I001
# ruff: noqa: I001

from beak.apps.abstract.entity import BaseEntity  # noqa
from beak.apps.analysis.entities.analysis import Analysis  # noqa
from beak.apps.analysis.entities.analysis import AnalysisCategory  # noqa
from beak.apps.analysis.entities.analysis import AnalysisCoding  # noqa
from beak.apps.analysis.entities.analysis import AnalysisInterim  # noqa
from beak.apps.analysis.entities.analysis import AnalysisRequest  # noqa
from beak.apps.analysis.entities.analysis import ClinicalData  # noqa
from beak.apps.analysis.entities.analysis import ClinicalDataCoding  # noqa
from beak.apps.analysis.entities.analysis import CodingStandard  # noqa
from beak.apps.analysis.entities.analysis import Profile  # noqa
from beak.apps.analysis.entities.analysis import ProfileCoding  # noqa
from beak.apps.analysis.entities.analysis import RejectionReason  # noqa
from beak.apps.analysis.entities.analysis import ResultOption  # noqa
from beak.apps.analysis.entities.analysis import Sample  # noqa
from beak.apps.analysis.entities.analysis import SampleType  # noqa
from beak.apps.analysis.entities.analysis import SampleTypeCoding  # noqa
from beak.apps.analysis.entities.qc import QCLevel  # noqa
from beak.apps.analysis.entities.qc import QCSet  # noqa
from beak.apps.analysis.entities.qc import QCTemplate  # noqa
from beak.apps.analysis.entities.results import AnalysisResult  # noqa
from beak.apps.analysis.entities.results import ResultMutation  # noqa
from beak.apps.analytics.entities import ReportMeta  # noqa
from beak.apps.app.entities import APPActivityLog  # noqa
from beak.apps.auditlog.entities import AuditLog  # noqa
from beak.apps.billing.entities import AnalysisDiscount  # noqa
from beak.apps.billing.entities import AnalysisPrice  # noqa
from beak.apps.billing.entities import ProfileDiscount  # noqa
from beak.apps.billing.entities import ProfilePrice  # noqa
from beak.apps.billing.entities import TestBill  # noqa
from beak.apps.billing.entities import TestBillInvoice  # noqa
from beak.apps.billing.entities import TestBillTransaction  # noqa
from beak.apps.billing.entities import VoucherCode  # noqa
from beak.apps.billing.entities import VoucherCustomer  # noqa
from beak.apps.client.entities import Client  # noqa
from beak.apps.client.entities import ClientContact  # noqa
from beak.apps.commune.sms.entities import SmsMessage  # noqa
from beak.apps.commune.sms.entities import SmsTemplate  # noqa
from beak.apps.document.entities import Document  # noqa
from beak.apps.document.entities import DocumentAudit  # noqa
from beak.apps.document.entities import DocumentCategory  # noqa
from beak.apps.document.entities import DocumentFolder  # noqa
from beak.apps.document.entities import DocumentReviewCycle  # noqa
from beak.apps.document.entities import DocumentReviewStep  # noqa
from beak.apps.document.entities import DocumentStatus  # noqa
from beak.apps.document.entities import DocumentSubscription  # noqa
from beak.apps.document.entities import DocumentTag  # noqa
from beak.apps.document.entities import DocumentTemplate  # noqa
from beak.apps.document.entities import DocumentVersion  # noqa
from beak.apps.grind.entities import GrindBoard  # noqa
from beak.apps.grind.entities import GrindErrand  # noqa
from beak.apps.grind.entities import GrindErrandDiscussion  # noqa
from beak.apps.grind.entities import GrindLabel  # noqa
from beak.apps.grind.entities import GrindMedia  # noqa
from beak.apps.grind.entities import GrindMilestone  # noqa
from beak.apps.grind.entities import GrindOccurrence  # noqa
from beak.apps.grind.entities import GrindPoster  # noqa
from beak.apps.grind.entities import GrindScheme  # noqa
from beak.apps.grind.entities import GrindStamp  # noqa
from beak.apps.idsequencer.entities import IdSequence  # noqa
from beak.apps.impress.entities import ReportImpress  # noqa
# from beak.apps.setup.entities import MethodValidation  # noqa
# from beak.apps.setup.entities import InstrumentCompetence  # noqa
from beak.apps.instrument.entities import CalibrationCertificate  # noqa
from beak.apps.instrument.entities import Instrument  # noqa
from beak.apps.instrument.entities import InstrumentCalibration  # noqa
from beak.apps.instrument.entities import InstrumentInterface  # noqa
from beak.apps.instrument.entities import InstrumentRawData  # noqa
from beak.apps.instrument.entities import InstrumentResultExclusions  # noqa
from beak.apps.instrument.entities import InstrumentResultTranslation  # noqa
from beak.apps.instrument.entities import InstrumentType  # noqa
from beak.apps.instrument.entities import LaboratoryInstrument  # noqa
from beak.apps.instrument.entities import Method  # noqa
from beak.apps.inventory.entities import Hazard  # noqa
from beak.apps.inventory.entities import StockAdjustment  # noqa
from beak.apps.inventory.entities import StockCategory  # noqa
from beak.apps.inventory.entities import StockItem  # noqa
from beak.apps.inventory.entities import StockItemVariant  # noqa
from beak.apps.inventory.entities import StockLot  # noqa
from beak.apps.inventory.entities import StockOrder  # noqa
from beak.apps.inventory.entities import StockOrderProduct  # noqa
from beak.apps.inventory.entities import StockProductInventory  # noqa
from beak.apps.inventory.entities import StockReceipt  # noqa
from beak.apps.inventory.entities import StockUnit  # noqa
from beak.apps.job.entities import Job  # noqa
from beak.apps.messaging.entities import Message  # noqa
from beak.apps.multiplex.microbiology.entities import AbxASTPanel  # noqa
from beak.apps.multiplex.microbiology.entities import AbxASTResult  # noqa
from beak.apps.multiplex.microbiology.entities import AbxAntibiotic  # noqa
from beak.apps.multiplex.microbiology.entities import AbxAntibioticGuideline  # noqa
from beak.apps.multiplex.microbiology.entities import AbxBreakpoint  # noqa
from beak.apps.multiplex.microbiology.entities import AbxBreakpointType  # noqa
from beak.apps.multiplex.microbiology.entities import AbxClass  # noqa
from beak.apps.multiplex.microbiology.entities import AbxExpResPhenotype  # noqa
from beak.apps.multiplex.microbiology.entities import AbxExpertInterpretationRule  # noqa
from beak.apps.multiplex.microbiology.entities import AbxFamily  # noqa
from beak.apps.multiplex.microbiology.entities import AbxGenus  # noqa
from beak.apps.multiplex.microbiology.entities import AbxGuideline  # noqa
from beak.apps.multiplex.microbiology.entities import AbxGuidelineYear  # noqa
from beak.apps.multiplex.microbiology.entities import AbxHost  # noqa
from beak.apps.multiplex.microbiology.entities import AbxKingdom  # noqa
from beak.apps.multiplex.microbiology.entities import AbxMedium  # noqa
from beak.apps.multiplex.microbiology.entities import AbxOrder  # noqa
from beak.apps.multiplex.microbiology.entities import AbxOrganism  # noqa
from beak.apps.multiplex.microbiology.entities import AbxOrganismResult  # noqa
from beak.apps.multiplex.microbiology.entities import AbxOrganismSerotype  # noqa
from beak.apps.multiplex.microbiology.entities import AbxPhylum  # noqa
from beak.apps.multiplex.microbiology.entities import AbxQCRange  # noqa
from beak.apps.multiplex.microbiology.entities import AbxSiteOfInfection  # noqa
from beak.apps.multiplex.microbiology.entities import AbxTestMethod  # noqa
from beak.apps.noticeboard.entities import Notice  # noqa
from beak.apps.notification.entities import ActivityFeed  # noqa
from beak.apps.notification.entities import ActivityStream  # noqa
from beak.apps.notification.entities import Notification  # noqa
from beak.apps.patient.entities import Identification  # noqa
from beak.apps.patient.entities import Patient  # noqa
from beak.apps.patient.entities import PatientIdentification  # noqa
from beak.apps.patient.search_indices import DateSearchIndex  # noqa
from beak.apps.patient.search_indices import PatientSearchIndex  # noqa
from beak.apps.patient.search_indices import PhoneSearchIndex  # noqa
from beak.apps.reflex.entities import ReflexAddAnalysis  # noqa
from beak.apps.reflex.entities import ReflexDecision  # noqa
from beak.apps.reflex.entities import ReflexDecisionExecution  # noqa
from beak.apps.reflex.entities import ReflexFinalizeAnalysis  # noqa
from beak.apps.reflex.entities import ReflexRule  # noqa
from beak.apps.reflex.entities import ReflexRuleCriteria  # noqa
from beak.apps.reflex.entities import ReflexRuleGroup  # noqa
from beak.apps.reflex.entities import ReflexTrigger  # noqa
from beak.apps.setup.entities import Country  # noqa
from beak.apps.setup.entities import Department  # noqa
from beak.apps.setup.entities import District  # noqa
from beak.apps.setup.entities import Laboratory  # noqa
from beak.apps.setup.entities import LaboratorySetting  # noqa
from beak.apps.setup.entities import Manufacturer  # noqa
from beak.apps.setup.entities import Organization  # noqa
from beak.apps.setup.entities import OrganizationSetting  # noqa
from beak.apps.setup.entities import Province  # noqa
from beak.apps.setup.entities import Supplier  # noqa
from beak.apps.setup.entities import Unit  # noqa
from beak.apps.shipment.entities import Shipment  # noqa
from beak.apps.shipment.entities import ShippedSample  # noqa
from beak.apps.storage.entities import StorageContainer  # noqa
from beak.apps.storage.entities import StorageLocation  # noqa
from beak.apps.storage.entities import StorageSection  # noqa
from beak.apps.storage.entities import StoreRoom  # noqa
from beak.apps.user.entities import Group  # noqa
from beak.apps.user.entities import Permission  # noqa
from beak.apps.user.entities import User  # noqa
from beak.apps.user.entities import UserPreference  # noqa
from beak.apps.worksheet.entities import WorkSheet  # noqa
from beak.apps.worksheet.entities import WorkSheetTemplate  # noqa
