# isort: skip_file
# skip-file
# ruff: noqa: I001
# ruff: noqa: I001

from beak.modules.core.abstract.entity import BaseEntity  # noqa
from beak.modules.core.analysis.entities.analysis import Analysis  # noqa
from beak.modules.core.analysis.entities.analysis import AnalysisCategory  # noqa
from beak.modules.core.analysis.entities.analysis import AnalysisCoding  # noqa
from beak.modules.core.analysis.entities.analysis import AnalysisInterim  # noqa
from beak.modules.core.analysis.entities.analysis import AnalysisRequest  # noqa
from beak.modules.core.analysis.entities.analysis import ClinicalData  # noqa
from beak.modules.core.analysis.entities.analysis import ClinicalDataCoding  # noqa
from beak.modules.core.analysis.entities.analysis import CodingStandard  # noqa
from beak.modules.core.analysis.entities.analysis import Profile  # noqa
from beak.modules.core.analysis.entities.analysis import ProfileCoding  # noqa
from beak.modules.core.analysis.entities.analysis import RejectionReason  # noqa
from beak.modules.core.analysis.entities.analysis import ResultOption  # noqa
from beak.modules.core.analysis.entities.analysis import Sample  # noqa
from beak.modules.core.analysis.entities.analysis import SampleType  # noqa
from beak.modules.core.analysis.entities.analysis import SampleTypeCoding  # noqa
from beak.modules.core.analysis.entities.qc import QCLevel  # noqa
from beak.modules.core.analysis.entities.qc import QCSet  # noqa
from beak.modules.core.analysis.entities.qc import QCTemplate  # noqa
from beak.modules.core.analysis.entities.results import AnalysisResult  # noqa
from beak.modules.core.analysis.entities.results import ResultMutation  # noqa
from beak.modules.core.analytics.entities import ReportMeta  # noqa
from beak.modules.core.app.entities import APPActivityLog  # noqa
from beak.modules.core.auditlog.entities import AuditLog  # noqa
from beak.modules.core.billing.entities import AnalysisDiscount  # noqa
from beak.modules.core.billing.entities import AnalysisPrice  # noqa
from beak.modules.core.billing.entities import ProfileDiscount  # noqa
from beak.modules.core.billing.entities import ProfilePrice  # noqa
from beak.modules.core.billing.entities import TestBill  # noqa
from beak.modules.core.billing.entities import TestBillInvoice  # noqa
from beak.modules.core.billing.entities import TestBillTransaction  # noqa
from beak.modules.core.billing.entities import VoucherCode  # noqa
from beak.modules.core.billing.entities import VoucherCustomer  # noqa
from beak.modules.core.client.entities import Client  # noqa
from beak.modules.core.client.entities import ClientContact  # noqa
from beak.modules.core.commune.sms.entities import SmsMessage  # noqa
from beak.modules.core.commune.sms.entities import SmsTemplate  # noqa
from beak.modules.core.document.entities import Document  # noqa
from beak.modules.core.document.entities import DocumentAudit  # noqa
from beak.modules.core.document.entities import DocumentCategory  # noqa
from beak.modules.core.document.entities import DocumentFolder  # noqa
from beak.modules.core.document.entities import DocumentReviewCycle  # noqa
from beak.modules.core.document.entities import DocumentReviewStep  # noqa
from beak.modules.core.document.entities import DocumentStatus  # noqa
from beak.modules.core.document.entities import DocumentSubscription  # noqa
from beak.modules.core.document.entities import DocumentTag  # noqa
from beak.modules.core.document.entities import DocumentTemplate  # noqa
from beak.modules.core.document.entities import DocumentVersion  # noqa
from beak.modules.core.grind.entities import GrindBoard  # noqa
from beak.modules.core.grind.entities import GrindErrand  # noqa
from beak.modules.core.grind.entities import GrindErrandDiscussion  # noqa
from beak.modules.core.grind.entities import GrindLabel  # noqa
from beak.modules.core.grind.entities import GrindMedia  # noqa
from beak.modules.core.grind.entities import GrindMilestone  # noqa
from beak.modules.core.grind.entities import GrindOccurrence  # noqa
from beak.modules.core.grind.entities import GrindPoster  # noqa
from beak.modules.core.grind.entities import GrindScheme  # noqa
from beak.modules.core.grind.entities import GrindStamp  # noqa
from beak.modules.core.idsequencer.entities import IdSequence  # noqa
from beak.modules.core.impress.entities import ReportImpress  # noqa
# from beak.modules.core.setup.entities import MethodValidation  # noqa
# from beak.modules.core.setup.entities import InstrumentCompetence  # noqa
from beak.modules.core.instrument.entities import CalibrationCertificate  # noqa
from beak.modules.core.instrument.entities import Instrument  # noqa
from beak.modules.core.instrument.entities import InstrumentCalibration  # noqa
from beak.modules.core.instrument.entities import InstrumentInterface  # noqa
from beak.modules.core.instrument.entities import InstrumentRawData  # noqa
from beak.modules.core.instrument.entities import InstrumentResultExclusions  # noqa
from beak.modules.core.instrument.entities import InstrumentResultTranslation  # noqa
from beak.modules.core.instrument.entities import InstrumentType  # noqa
from beak.modules.core.instrument.entities import LaboratoryInstrument  # noqa
from beak.modules.core.instrument.entities import Method  # noqa
from beak.modules.core.inventory.entities import Hazard  # noqa
from beak.modules.core.inventory.entities import StockAdjustment  # noqa
from beak.modules.core.inventory.entities import StockCategory  # noqa
from beak.modules.core.inventory.entities import StockItem  # noqa
from beak.modules.core.inventory.entities import StockItemVariant  # noqa
from beak.modules.core.inventory.entities import StockLot  # noqa
from beak.modules.core.inventory.entities import StockOrder  # noqa
from beak.modules.core.inventory.entities import StockOrderProduct  # noqa
from beak.modules.core.inventory.entities import StockProductInventory  # noqa
from beak.modules.core.inventory.entities import StockReceipt  # noqa
from beak.modules.core.inventory.entities import StockUnit  # noqa
from beak.modules.core.job.entities import Job  # noqa
from beak.modules.core.messaging.entities import Message  # noqa
from beak.modules.clinical.microbiology.entities import AbxASTPanel  # noqa
from beak.modules.clinical.microbiology.entities import AbxASTResult  # noqa
from beak.modules.clinical.microbiology.entities import AbxAntibiotic  # noqa
from beak.modules.clinical.microbiology.entities import AbxAntibioticGuideline  # noqa
from beak.modules.clinical.microbiology.entities import AbxBreakpoint  # noqa
from beak.modules.clinical.microbiology.entities import AbxBreakpointType  # noqa
from beak.modules.clinical.microbiology.entities import AbxClass  # noqa
from beak.modules.clinical.microbiology.entities import AbxExpResPhenotype  # noqa
from beak.modules.clinical.microbiology.entities import AbxExpertInterpretationRule  # noqa
from beak.modules.clinical.microbiology.entities import AbxFamily  # noqa
from beak.modules.clinical.microbiology.entities import AbxGenus  # noqa
from beak.modules.clinical.microbiology.entities import AbxGuideline  # noqa
from beak.modules.clinical.microbiology.entities import AbxGuidelineYear  # noqa
from beak.modules.clinical.microbiology.entities import AbxHost  # noqa
from beak.modules.clinical.microbiology.entities import AbxKingdom  # noqa
from beak.modules.clinical.microbiology.entities import AbxMedium  # noqa
from beak.modules.clinical.microbiology.entities import AbxOrder  # noqa
from beak.modules.clinical.microbiology.entities import AbxOrganism  # noqa
from beak.modules.clinical.microbiology.entities import AbxOrganismResult  # noqa
from beak.modules.clinical.microbiology.entities import AbxOrganismSerotype  # noqa
from beak.modules.clinical.microbiology.entities import AbxPhylum  # noqa
from beak.modules.clinical.microbiology.entities import AbxQCRange  # noqa
from beak.modules.clinical.microbiology.entities import AbxSiteOfInfection  # noqa
from beak.modules.clinical.microbiology.entities import AbxTestMethod  # noqa
from beak.modules.core.noticeboard.entities import Notice  # noqa
from beak.modules.core.notification.entities import ActivityFeed  # noqa
from beak.modules.core.notification.entities import ActivityStream  # noqa
from beak.modules.core.notification.entities import Notification  # noqa
from beak.modules.clinical.patient.entities import Identification  # noqa
from beak.modules.clinical.patient.entities import Patient  # noqa
from beak.modules.clinical.patient.entities import PatientAnalysisRequestLink  # noqa
from beak.modules.clinical.patient.entities import PatientIdentification  # noqa
from beak.modules.clinical.patient.search_indices import DateSearchIndex  # noqa
from beak.modules.clinical.patient.search_indices import PatientSearchIndex  # noqa
from beak.modules.clinical.patient.search_indices import PhoneSearchIndex  # noqa
from beak.modules.core.reflex.entities import ReflexAddAnalysis  # noqa
from beak.modules.core.reflex.entities import ReflexDecision  # noqa
from beak.modules.core.reflex.entities import ReflexDecisionExecution  # noqa
from beak.modules.core.reflex.entities import ReflexFinalizeAnalysis  # noqa
from beak.modules.core.reflex.entities import ReflexRule  # noqa
from beak.modules.core.reflex.entities import ReflexRuleCriteria  # noqa
from beak.modules.core.reflex.entities import ReflexRuleGroup  # noqa
from beak.modules.core.reflex.entities import ReflexTrigger  # noqa
from beak.modules.core.setup.entities import Country  # noqa
from beak.modules.core.setup.entities import Department  # noqa
from beak.modules.core.setup.entities import District  # noqa
from beak.modules.core.setup.entities import Laboratory  # noqa
from beak.modules.core.setup.entities import LaboratorySetting  # noqa
from beak.modules.core.setup.entities import Manufacturer  # noqa
from beak.modules.core.setup.entities import Organization  # noqa
from beak.modules.core.setup.entities import OrganizationSetting  # noqa
from beak.modules.core.setup.entities import Province  # noqa
from beak.modules.core.setup.entities import Supplier  # noqa
from beak.modules.core.setup.entities import Unit  # noqa
from beak.modules.core.shipment.entities import Shipment  # noqa
from beak.modules.core.shipment.entities import ShippedSample  # noqa
from beak.modules.core.storage.entities import StorageContainer  # noqa
from beak.modules.core.storage.entities import StorageLocation  # noqa
from beak.modules.core.storage.entities import StorageSection  # noqa
from beak.modules.core.storage.entities import StoreRoom  # noqa
from beak.modules.core.identity.entities import Group  # noqa
from beak.modules.core.identity.entities import Permission  # noqa
from beak.modules.core.identity.entities import User  # noqa
from beak.modules.core.identity.entities import UserPreference  # noqa
from beak.modules.core.worksheet.entities import WorkSheet  # noqa
from beak.modules.core.worksheet.entities import WorkSheetTemplate  # noqa
