"""add billing caps

Revision ID: 749af294334a
Revises: 
Create Date: 2026-02-21 18:27:41.155890

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '749af294334a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_audit_log',
    sa.Column('tenant_slug', sa.String(length=128), nullable=True),
    sa.Column('actor_identifier', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('resource_type', sa.String(length=128), nullable=False),
    sa.Column('resource_uid', sa.String(length=64), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('uid', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    schema='platform'
    )
    op.create_index(op.f('ix_platform_billing_audit_log_tenant_slug'), 'billing_audit_log', ['tenant_slug'], unique=False, schema='platform')
    op.create_index(op.f('ix_platform_billing_audit_log_uid'), 'billing_audit_log', ['uid'], unique=False, schema='platform')
    op.create_table('billing_customer',
    sa.Column('tenant_slug', sa.String(length=128), nullable=False),
    sa.Column('customer_uid', sa.String(length=64), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('billing_email', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('country', sa.String(length=8), nullable=True),
    sa.Column('provider_preference', sa.String(length=32), nullable=False),
    sa.Column('auto_finalize_invoices', sa.Boolean(), nullable=False),
    sa.Column('auto_send_invoices', sa.Boolean(), nullable=False),
    sa.Column('payment_terms_days', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('uid', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('tenant_slug', 'uid'),
    schema='platform'
    )
    op.create_index(op.f('ix_platform_billing_customer_tenant_slug'), 'billing_customer', ['tenant_slug'], unique=True, schema='platform')
    op.create_index(op.f('ix_platform_billing_customer_uid'), 'billing_customer', ['uid'], unique=False, schema='platform')
    op.create_table('billing_invoice',
    sa.Column('tenant_slug', sa.String(length=128), nullable=False),
    sa.Column('invoice_number', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('amount_due', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('finalized_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('uid', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    schema='platform'
    )
    op.create_index(op.f('ix_platform_billing_invoice_tenant_slug'), 'billing_invoice', ['tenant_slug'], unique=False, schema='platform')
    op.create_index(op.f('ix_platform_billing_invoice_uid'), 'billing_invoice', ['uid'], unique=False, schema='platform')
    op.create_index('uq_billing_invoice_invoice_number', 'billing_invoice', ['invoice_number'], unique=True, schema='platform')
    op.create_table('billing_invoice_line',
    sa.Column('invoice_uid', sa.String(length=64), nullable=False),
    sa.Column('line_index', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('uid', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    schema='platform'
    )
    op.create_index(op.f('ix_platform_billing_invoice_line_invoice_uid'), 'billing_invoice_line', ['invoice_uid'], unique=False, schema='platform')
    op.create_index(op.f('ix_platform_billing_invoice_line_uid'), 'billing_invoice_line', ['uid'], unique=False, schema='platform')
    op.create_table('billing_payment_allocation',
    sa.Column('payment_attempt_uid', sa.String(length=64), nullable=False),
    sa.Column('invoice_uid', sa.String(length=64), nullable=False),
    sa.Column('tenant_slug', sa.String(length=128), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('uid', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    schema='platform'
    )
    op.create_index(op.f('ix_platform_billing_payment_allocation_invoice_uid'), 'billing_payment_allocation', ['invoice_uid'], unique=False, schema='platform')
    op.create_index(op.f('ix_platform_billing_payment_allocation_payment_attempt_uid'), 'billing_payment_allocation', ['payment_attempt_uid'], unique=False, schema='platform')
    op.create_index(op.f('ix_platform_billing_payment_allocation_tenant_slug'), 'billing_payment_allocation', ['tenant_slug'], unique=False, schema='platform')
    op.create_index(op.f('ix_platform_billing_payment_allocation_uid'), 'billing_payment_allocation', ['uid'], unique=False, schema='platform')
    op.create_table('billing_payment_attempt',
    sa.Column('invoice_uid', sa.String(length=64), nullable=False),
    sa.Column('tenant_slug', sa.String(length=128), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('provider_reference', sa.String(length=255), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('uid', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    schema='platform'
    )
    op.create_index(op.f('ix_platform_billing_payment_attempt_invoice_uid'), 'billing_payment_attempt', ['invoice_uid'], unique=False, schema='platform')
    op.create_index(op.f('ix_platform_billing_payment_attempt_tenant_slug'), 'billing_payment_attempt', ['tenant_slug'], unique=False, schema='platform')
    op.create_index(op.f('ix_platform_billing_payment_attempt_uid'), 'billing_payment_attempt', ['uid'], unique=False, schema='platform')
    op.create_table('billing_payment_proof',
    sa.Column('tenant_slug', sa.String(length=128), nullable=False),
    sa.Column('invoice_uid', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('payment_method', sa.String(length=64), nullable=True),
    sa.Column('payment_reference', sa.String(length=255), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('bucket_name', sa.String(length=128), nullable=False),
    sa.Column('object_name', sa.String(length=512), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('uid', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    schema='platform'
    )
    op.create_index(op.f('ix_platform_billing_payment_proof_invoice_uid'), 'billing_payment_proof', ['invoice_uid'], unique=False, schema='platform')
    op.create_index(op.f('ix_platform_billing_payment_proof_tenant_slug'), 'billing_payment_proof', ['tenant_slug'], unique=False, schema='platform')
    op.create_index(op.f('ix_platform_billing_payment_proof_uid'), 'billing_payment_proof', ['uid'], unique=False, schema='platform')
    op.create_table('billing_plan',
    sa.Column('plan_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('uid', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('plan_code'),
    schema='platform'
    )
    op.create_index(op.f('ix_platform_billing_plan_uid'), 'billing_plan', ['uid'], unique=False, schema='platform')
    op.create_table('billing_plan_feature',
    sa.Column('plan_uid', sa.String(length=64), nullable=False),
    sa.Column('feature_key', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('included_units', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('uid', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    schema='platform'
    )
    op.create_index(op.f('ix_platform_billing_plan_feature_plan_uid'), 'billing_plan_feature', ['plan_uid'], unique=False, schema='platform')
    op.create_index(op.f('ix_platform_billing_plan_feature_uid'), 'billing_plan_feature', ['uid'], unique=False, schema='platform')
    op.create_table('billing_plan_limit',
    sa.Column('plan_uid', sa.String(length=64), nullable=False),
    sa.Column('metric_key', sa.String(length=64), nullable=False),
    sa.Column('limit_value', sa.Integer(), nullable=False),
    sa.Column('limit_window', sa.String(length=16), nullable=False),
    sa.Column('enforcement_mode', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('uid', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    schema='platform'
    )
    op.create_index(op.f('ix_platform_billing_plan_limit_plan_uid'), 'billing_plan_limit', ['plan_uid'], unique=False, schema='platform')
    op.create_index(op.f('ix_platform_billing_plan_limit_uid'), 'billing_plan_limit', ['uid'], unique=False, schema='platform')
    op.create_table('billing_provider_account_config',
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('account_name', sa.String(length=128), nullable=True),
    sa.Column('account_reference', sa.String(length=255), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('uid', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    schema='platform'
    )
    op.create_index(op.f('ix_platform_billing_provider_account_config_uid'), 'billing_provider_account_config', ['uid'], unique=False, schema='platform')
    op.create_table('billing_subscription',
    sa.Column('tenant_slug', sa.String(length=128), nullable=False),
    sa.Column('plan_code', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('usage_overage_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('mrr_snapshot', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('next_billing_date', sa.Date(), nullable=True),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('paused_at', sa.DateTime(), nullable=True),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('uid', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    schema='platform'
    )
    op.create_index(op.f('ix_platform_billing_subscription_tenant_slug'), 'billing_subscription', ['tenant_slug'], unique=False, schema='platform')
    op.create_index(op.f('ix_platform_billing_subscription_uid'), 'billing_subscription', ['uid'], unique=False, schema='platform')
    op.create_table('billing_subscription_item',
    sa.Column('subscription_uid', sa.String(length=64), nullable=False),
    sa.Column('tenant_slug', sa.String(length=128), nullable=False),
    sa.Column('item_code', sa.String(length=128), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('uid', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    schema='platform'
    )
    op.create_index(op.f('ix_platform_billing_subscription_item_subscription_uid'), 'billing_subscription_item', ['subscription_uid'], unique=False, schema='platform')
    op.create_index(op.f('ix_platform_billing_subscription_item_tenant_slug'), 'billing_subscription_item', ['tenant_slug'], unique=False, schema='platform')
    op.create_index(op.f('ix_platform_billing_subscription_item_uid'), 'billing_subscription_item', ['uid'], unique=False, schema='platform')
    op.create_table('billing_tenant_override',
    sa.Column('tenant_slug', sa.String(length=128), nullable=False),
    sa.Column('metric_key', sa.String(length=64), nullable=True),
    sa.Column('feature_key', sa.String(length=64), nullable=True),
    sa.Column('override_limit_value', sa.Integer(), nullable=True),
    sa.Column('override_enabled', sa.Boolean(), nullable=True),
    sa.Column('limit_window', sa.String(length=16), nullable=True),
    sa.Column('enforcement_mode', sa.String(length=32), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('uid', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    schema='platform'
    )
    op.create_index(op.f('ix_platform_billing_tenant_override_tenant_slug'), 'billing_tenant_override', ['tenant_slug'], unique=False, schema='platform')
    op.create_index(op.f('ix_platform_billing_tenant_override_uid'), 'billing_tenant_override', ['uid'], unique=False, schema='platform')
    op.create_table('billing_usage_counter',
    sa.Column('tenant_slug', sa.String(length=128), nullable=False),
    sa.Column('metric_key', sa.String(length=64), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.Column('window_end', sa.DateTime(), nullable=False),
    sa.Column('scope_user_uid', sa.String(length=64), nullable=True),
    sa.Column('scope_lab_uid', sa.String(length=64), nullable=True),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('uid', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    schema='platform'
    )
    op.create_index(op.f('ix_platform_billing_usage_counter_tenant_slug'), 'billing_usage_counter', ['tenant_slug'], unique=False, schema='platform')
    op.create_index(op.f('ix_platform_billing_usage_counter_uid'), 'billing_usage_counter', ['uid'], unique=False, schema='platform')
    op.create_table('billing_usage_record_daily',
    sa.Column('tenant_slug', sa.String(length=128), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('metric_key', sa.String(length=128), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('uid', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    schema='platform'
    )
    op.create_index(op.f('ix_platform_billing_usage_record_daily_tenant_slug'), 'billing_usage_record_daily', ['tenant_slug'], unique=False, schema='platform')
    op.create_index(op.f('ix_platform_billing_usage_record_daily_uid'), 'billing_usage_record_daily', ['uid'], unique=False, schema='platform')
    op.create_table('billing_webhook_event',
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('uid', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    schema='platform'
    )
    op.create_index(op.f('ix_platform_billing_webhook_event_uid'), 'billing_webhook_event', ['uid'], unique=False, schema='platform')
    op.create_index('uq_billing_webhook_event_idempotency_key', 'billing_webhook_event', ['idempotency_key'], unique=True, schema='platform')
    op.create_table('platform_role',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('uid', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('name'),
    schema='platform'
    )
    op.create_index(op.f('ix_platform_platform_role_uid'), 'platform_role', ['uid'], unique=False, schema='platform')
    op.create_table('platform_user',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('uid', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    schema='platform'
    )
    op.create_index(op.f('ix_platform_platform_user_uid'), 'platform_user', ['uid'], unique=False, schema='platform')
    op.create_table('tenant',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('schema_name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('admin_email', sa.String(length=255), nullable=True),
    sa.Column('primary_industry', sa.String(length=32), nullable=True),
    sa.Column('enabled_modules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('module_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('provisioned_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('uid', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('schema_name'),
    sa.UniqueConstraint('slug'),
    schema='platform'
    )
    op.create_index(op.f('ix_platform_tenant_uid'), 'tenant', ['uid'], unique=False, schema='platform')
    op.create_table('platform_user_role',
    sa.Column('user_uid', sa.String(length=64), nullable=False),
    sa.Column('role_uid', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_uid'], ['platform.platform_role.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_uid'], ['platform.platform_user.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_uid', 'role_uid', name='pk_platform_user_role'),
    schema='platform'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('platform_user_role', schema='platform')
    op.drop_index(op.f('ix_platform_tenant_uid'), table_name='tenant', schema='platform')
    op.drop_table('tenant', schema='platform')
    op.drop_index(op.f('ix_platform_platform_user_uid'), table_name='platform_user', schema='platform')
    op.drop_table('platform_user', schema='platform')
    op.drop_index(op.f('ix_platform_platform_role_uid'), table_name='platform_role', schema='platform')
    op.drop_table('platform_role', schema='platform')
    op.drop_index('uq_billing_webhook_event_idempotency_key', table_name='billing_webhook_event', schema='platform')
    op.drop_index(op.f('ix_platform_billing_webhook_event_uid'), table_name='billing_webhook_event', schema='platform')
    op.drop_table('billing_webhook_event', schema='platform')
    op.drop_index(op.f('ix_platform_billing_usage_record_daily_uid'), table_name='billing_usage_record_daily', schema='platform')
    op.drop_index(op.f('ix_platform_billing_usage_record_daily_tenant_slug'), table_name='billing_usage_record_daily', schema='platform')
    op.drop_table('billing_usage_record_daily', schema='platform')
    op.drop_index(op.f('ix_platform_billing_usage_counter_uid'), table_name='billing_usage_counter', schema='platform')
    op.drop_index(op.f('ix_platform_billing_usage_counter_tenant_slug'), table_name='billing_usage_counter', schema='platform')
    op.drop_table('billing_usage_counter', schema='platform')
    op.drop_index(op.f('ix_platform_billing_tenant_override_uid'), table_name='billing_tenant_override', schema='platform')
    op.drop_index(op.f('ix_platform_billing_tenant_override_tenant_slug'), table_name='billing_tenant_override', schema='platform')
    op.drop_table('billing_tenant_override', schema='platform')
    op.drop_index(op.f('ix_platform_billing_subscription_item_uid'), table_name='billing_subscription_item', schema='platform')
    op.drop_index(op.f('ix_platform_billing_subscription_item_tenant_slug'), table_name='billing_subscription_item', schema='platform')
    op.drop_index(op.f('ix_platform_billing_subscription_item_subscription_uid'), table_name='billing_subscription_item', schema='platform')
    op.drop_table('billing_subscription_item', schema='platform')
    op.drop_index(op.f('ix_platform_billing_subscription_uid'), table_name='billing_subscription', schema='platform')
    op.drop_index(op.f('ix_platform_billing_subscription_tenant_slug'), table_name='billing_subscription', schema='platform')
    op.drop_table('billing_subscription', schema='platform')
    op.drop_index(op.f('ix_platform_billing_provider_account_config_uid'), table_name='billing_provider_account_config', schema='platform')
    op.drop_table('billing_provider_account_config', schema='platform')
    op.drop_index(op.f('ix_platform_billing_plan_limit_uid'), table_name='billing_plan_limit', schema='platform')
    op.drop_index(op.f('ix_platform_billing_plan_limit_plan_uid'), table_name='billing_plan_limit', schema='platform')
    op.drop_table('billing_plan_limit', schema='platform')
    op.drop_index(op.f('ix_platform_billing_plan_feature_uid'), table_name='billing_plan_feature', schema='platform')
    op.drop_index(op.f('ix_platform_billing_plan_feature_plan_uid'), table_name='billing_plan_feature', schema='platform')
    op.drop_table('billing_plan_feature', schema='platform')
    op.drop_index(op.f('ix_platform_billing_plan_uid'), table_name='billing_plan', schema='platform')
    op.drop_table('billing_plan', schema='platform')
    op.drop_index(op.f('ix_platform_billing_payment_proof_uid'), table_name='billing_payment_proof', schema='platform')
    op.drop_index(op.f('ix_platform_billing_payment_proof_tenant_slug'), table_name='billing_payment_proof', schema='platform')
    op.drop_index(op.f('ix_platform_billing_payment_proof_invoice_uid'), table_name='billing_payment_proof', schema='platform')
    op.drop_table('billing_payment_proof', schema='platform')
    op.drop_index(op.f('ix_platform_billing_payment_attempt_uid'), table_name='billing_payment_attempt', schema='platform')
    op.drop_index(op.f('ix_platform_billing_payment_attempt_tenant_slug'), table_name='billing_payment_attempt', schema='platform')
    op.drop_index(op.f('ix_platform_billing_payment_attempt_invoice_uid'), table_name='billing_payment_attempt', schema='platform')
    op.drop_table('billing_payment_attempt', schema='platform')
    op.drop_index(op.f('ix_platform_billing_payment_allocation_uid'), table_name='billing_payment_allocation', schema='platform')
    op.drop_index(op.f('ix_platform_billing_payment_allocation_tenant_slug'), table_name='billing_payment_allocation', schema='platform')
    op.drop_index(op.f('ix_platform_billing_payment_allocation_payment_attempt_uid'), table_name='billing_payment_allocation', schema='platform')
    op.drop_index(op.f('ix_platform_billing_payment_allocation_invoice_uid'), table_name='billing_payment_allocation', schema='platform')
    op.drop_table('billing_payment_allocation', schema='platform')
    op.drop_index(op.f('ix_platform_billing_invoice_line_uid'), table_name='billing_invoice_line', schema='platform')
    op.drop_index(op.f('ix_platform_billing_invoice_line_invoice_uid'), table_name='billing_invoice_line', schema='platform')
    op.drop_table('billing_invoice_line', schema='platform')
    op.drop_index('uq_billing_invoice_invoice_number', table_name='billing_invoice', schema='platform')
    op.drop_index(op.f('ix_platform_billing_invoice_uid'), table_name='billing_invoice', schema='platform')
    op.drop_index(op.f('ix_platform_billing_invoice_tenant_slug'), table_name='billing_invoice', schema='platform')
    op.drop_table('billing_invoice', schema='platform')
    op.drop_index(op.f('ix_platform_billing_customer_uid'), table_name='billing_customer', schema='platform')
    op.drop_index(op.f('ix_platform_billing_customer_tenant_slug'), table_name='billing_customer', schema='platform')
    op.drop_table('billing_customer', schema='platform')
    op.drop_index(op.f('ix_platform_billing_audit_log_uid'), table_name='billing_audit_log', schema='platform')
    op.drop_index(op.f('ix_platform_billing_audit_log_tenant_slug'), table_name='billing_audit_log', schema='platform')
    op.drop_table('billing_audit_log', schema='platform')
    # ### end Alembic commands ###
