from .department import DepartmentType
from .setup import (
    CountryType,
    DistrictCursorPage,
    DistrictEdge,
    DistrictType,
    OrganizationSettingType,
    OrganizationType,
    LaboratorySettingType,
    LaboratoryType,
    LaboratoryCursorPage,
    LaboratoryEdge,
    ManufacturerType,
    ProvinceCursorPage,
    ProvinceEdge,
    ProvinceType,
    SupplierType,
    UnitType,
)

setup_types = [
    OrganizationSettingType,
    OrganizationType,
    LaboratoryCursorPage,
    LaboratoryType,
    LaboratoryEdge,
    LaboratorySettingType,
    SupplierType,
    ManufacturerType,
    UnitType,
    CountryType,
    ProvinceType,
    ProvinceEdge,
    ProvinceCursorPage,
    DistrictType,
    DistrictEdge,
    DistrictCursorPage,
    DepartmentType,
]
