"""add reflex coodinates

Revision ID: d3943ec13098
Revises: 63ff64eb6c5d
Create Date: 2026-01-12 07:38:00.662409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3943ec13098'
down_revision = '63ff64eb6c5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reflex_add_analysis', sa.Column('pos_x', sa.Float(), nullable=True))
    op.add_column('reflex_add_analysis', sa.Column('pos_y', sa.Float(), nullable=True))
    op.add_column('reflex_decision', sa.Column('pos_x', sa.Float(), nullable=True))
    op.add_column('reflex_decision', sa.Column('pos_y', sa.Float(), nullable=True))
    op.add_column('reflex_finalize_analysis', sa.Column('pos_x', sa.Float(), nullable=True))
    op.add_column('reflex_finalize_analysis', sa.Column('pos_y', sa.Float(), nullable=True))
    op.add_column('reflex_rule_group', sa.Column('pos_x', sa.Float(), nullable=True))
    op.add_column('reflex_rule_group', sa.Column('pos_y', sa.Float(), nullable=True))
    op.add_column('reflex_trigger', sa.Column('pos_x', sa.Float(), nullable=True))
    op.add_column('reflex_trigger', sa.Column('pos_y', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reflex_trigger', 'pos_y')
    op.drop_column('reflex_trigger', 'pos_x')
    op.drop_column('reflex_rule_group', 'pos_y')
    op.drop_column('reflex_rule_group', 'pos_x')
    op.drop_column('reflex_finalize_analysis', 'pos_y')
    op.drop_column('reflex_finalize_analysis', 'pos_x')
    op.drop_column('reflex_decision', 'pos_y')
    op.drop_column('reflex_decision', 'pos_x')
    op.drop_column('reflex_add_analysis', 'pos_y')
    op.drop_column('reflex_add_analysis', 'pos_x')
    # ### end Alembic commands ###
