"""add mega_menu to user_preference

Revision ID: bf2a10490c6f
Revises: d3943ec13098
Create Date: 2026-02-11 02:11:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf2a10490c6f'
down_revision = 'd3943ec13098'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preference', sa.Column('mega_menu', sa.Boolean(), nullable=True, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_preference', 'mega_menu')
    # ### end Alembic commands ###
