"""Add named FK constraints to break circular dependency

Revision ID: 95e1f4841994
Revises: 3f6b7c8d9e10
Create Date: 2026-01-04 14:36:03.075152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95e1f4841994'
down_revision = '3f6b7c8d9e10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_sample_relationship_laboratory_uid'), 'sample_relationship', ['laboratory_uid'], unique=False)
    op.create_index(op.f('ix_sample_relationship_uid'), 'sample_relationship', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sample_relationship_uid'), table_name='sample_relationship')
    op.drop_index(op.f('ix_sample_relationship_laboratory_uid'), table_name='sample_relationship')
    # ### end Alembic commands ###
