"""simplified reflexing

Revision ID: 63ff64eb6c5d
Revises: 95e1f4841994
Create Date: 2026-01-11 17:18:00.826120

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '63ff64eb6c5d'
down_revision = '95e1f4841994'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reflex_trigger',
                    sa.Column('reflex_rule_uid', sa.String(), nullable=False),
                    sa.Column('level', sa.Integer(), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('sample_type_uid', sa.String(), nullable=True),
                    sa.Column('laboratory_uid', sa.String(), nullable=False),
                    sa.Column('uid', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by_uid', sa.String(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_by_uid', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['created_by_uid'], ['user.uid'], name='fk_reflex_trigger_created_by'),
                    sa.ForeignKeyConstraint(['laboratory_uid'], ['laboratory.uid'],
                                            name='fk_reflex_trigger_laboratory'),
                    sa.ForeignKeyConstraint(['reflex_rule_uid'], ['reflex_rule.uid'], ),
                    sa.ForeignKeyConstraint(['sample_type_uid'], ['sample_type.uid'], ),
                    sa.ForeignKeyConstraint(['updated_by_uid'], ['user.uid'], name='fk_reflex_trigger_updated_by'),
                    sa.PrimaryKeyConstraint('uid')
                    )
    op.create_index(op.f('ix_reflex_trigger_laboratory_uid'), 'reflex_trigger', ['laboratory_uid'], unique=False)
    op.create_index(op.f('ix_reflex_trigger_reflex_rule_uid'), 'reflex_trigger', ['reflex_rule_uid'], unique=False)
    op.create_index(op.f('ix_reflex_trigger_uid'), 'reflex_trigger', ['uid'], unique=False)
    op.create_table('reflex_decision',
                    sa.Column('reflex_trigger_uid', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('priority', sa.Integer(), nullable=True),
                    sa.Column('laboratory_uid', sa.String(), nullable=False),
                    sa.Column('uid', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by_uid', sa.String(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_by_uid', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['created_by_uid'], ['user.uid'], name='fk_reflex_decision_created_by'),
                    sa.ForeignKeyConstraint(['laboratory_uid'], ['laboratory.uid'],
                                            name='fk_reflex_decision_laboratory'),
                    sa.ForeignKeyConstraint(['reflex_trigger_uid'], ['reflex_trigger.uid'], ),
                    sa.ForeignKeyConstraint(['updated_by_uid'], ['user.uid'], name='fk_reflex_decision_updated_by'),
                    sa.PrimaryKeyConstraint('uid')
                    )
    op.create_index(op.f('ix_reflex_decision_laboratory_uid'), 'reflex_decision', ['laboratory_uid'], unique=False)
    op.create_index(op.f('ix_reflex_decision_reflex_trigger_uid'), 'reflex_decision', ['reflex_trigger_uid'],
                    unique=False)
    op.create_index(op.f('ix_reflex_decision_uid'), 'reflex_decision', ['uid'], unique=False)
    op.create_table('reflex_trigger_analysis',
                    sa.Column('analysis_uid', sa.String(), nullable=False),
                    sa.Column('reflex_trigger_uid', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['analysis_uid'], ['analysis.uid'], ),
                    sa.ForeignKeyConstraint(['reflex_trigger_uid'], ['reflex_trigger.uid'], ),
                    sa.PrimaryKeyConstraint('analysis_uid', 'reflex_trigger_uid')
                    )
    op.create_table('reflex_add_analysis',
                    sa.Column('reflex_decision_uid', sa.String(), nullable=False),
                    sa.Column('analysis_uid', sa.String(), nullable=False),
                    sa.Column('count', sa.Integer(), nullable=True),
                    sa.Column('laboratory_uid', sa.String(), nullable=False),
                    sa.Column('uid', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by_uid', sa.String(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_by_uid', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['analysis_uid'], ['analysis.uid'], ),
                    sa.ForeignKeyConstraint(['created_by_uid'], ['user.uid'], name='fk_reflex_add_analysis_created_by'),
                    sa.ForeignKeyConstraint(['laboratory_uid'], ['laboratory.uid'],
                                            name='fk_reflex_add_analysis_laboratory'),
                    sa.ForeignKeyConstraint(['reflex_decision_uid'], ['reflex_decision.uid'], ),
                    sa.ForeignKeyConstraint(['updated_by_uid'], ['user.uid'], name='fk_reflex_add_analysis_updated_by'),
                    sa.PrimaryKeyConstraint('uid')
                    )
    op.create_index(op.f('ix_reflex_add_analysis_laboratory_uid'), 'reflex_add_analysis', ['laboratory_uid'],
                    unique=False)
    op.create_index(op.f('ix_reflex_add_analysis_reflex_decision_uid'), 'reflex_add_analysis', ['reflex_decision_uid'],
                    unique=False)
    op.create_index(op.f('ix_reflex_add_analysis_uid'), 'reflex_add_analysis', ['uid'], unique=False)
    op.create_table('reflex_finalize_analysis',
                    sa.Column('reflex_decision_uid', sa.String(), nullable=False),
                    sa.Column('analysis_uid', sa.String(), nullable=False),
                    sa.Column('value', sa.String(), nullable=False),
                    sa.Column('laboratory_uid', sa.String(), nullable=False),
                    sa.Column('uid', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by_uid', sa.String(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_by_uid', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['analysis_uid'], ['analysis.uid'], ),
                    sa.ForeignKeyConstraint(['created_by_uid'], ['user.uid'],
                                            name='fk_reflex_finalize_analysis_created_by'),
                    sa.ForeignKeyConstraint(['laboratory_uid'], ['laboratory.uid'],
                                            name='fk_reflex_finalize_analysis_laboratory'),
                    sa.ForeignKeyConstraint(['reflex_decision_uid'], ['reflex_decision.uid'], ),
                    sa.ForeignKeyConstraint(['updated_by_uid'], ['user.uid'],
                                            name='fk_reflex_finalize_analysis_updated_by'),
                    sa.PrimaryKeyConstraint('uid')
                    )
    op.create_index(op.f('ix_reflex_finalize_analysis_laboratory_uid'), 'reflex_finalize_analysis', ['laboratory_uid'],
                    unique=False)
    op.create_index(op.f('ix_reflex_finalize_analysis_reflex_decision_uid'), 'reflex_finalize_analysis',
                    ['reflex_decision_uid'], unique=False)
    op.create_index(op.f('ix_reflex_finalize_analysis_uid'), 'reflex_finalize_analysis', ['uid'], unique=False)
    op.create_table('reflex_rule_group',
                    sa.Column('reflex_decision_uid', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('priority', sa.Integer(), nullable=True),
                    sa.Column('laboratory_uid', sa.String(), nullable=False),
                    sa.Column('uid', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by_uid', sa.String(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_by_uid', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['created_by_uid'], ['user.uid'], name='fk_reflex_rule_group_created_by'),
                    sa.ForeignKeyConstraint(['laboratory_uid'], ['laboratory.uid'],
                                            name='fk_reflex_rule_group_laboratory'),
                    sa.ForeignKeyConstraint(['reflex_decision_uid'], ['reflex_decision.uid'], ),
                    sa.ForeignKeyConstraint(['updated_by_uid'], ['user.uid'], name='fk_reflex_rule_group_updated_by'),
                    sa.PrimaryKeyConstraint('uid')
                    )
    op.create_index(op.f('ix_reflex_rule_group_laboratory_uid'), 'reflex_rule_group', ['laboratory_uid'], unique=False)
    op.create_index(op.f('ix_reflex_rule_group_reflex_decision_uid'), 'reflex_rule_group', ['reflex_decision_uid'],
                    unique=False)
    op.create_index(op.f('ix_reflex_rule_group_uid'), 'reflex_rule_group', ['uid'], unique=False)
    op.create_table('reflex_decision_execution',
                    sa.Column('sample_uid', sa.String(), nullable=False),
                    sa.Column('reflex_decision_uid', sa.String(), nullable=False),
                    sa.Column('status', sa.String(), nullable=False),
                    sa.Column('uid', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by_uid', sa.String(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_by_uid', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['created_by_uid'], ['user.uid'],
                                            name='fk_reflex_decision_execution_created_by'),
                    sa.ForeignKeyConstraint(['reflex_decision_uid'], ['reflex_decision.uid'], ),
                    sa.ForeignKeyConstraint(['sample_uid'], ['sample.uid'], ),
                    sa.ForeignKeyConstraint(['updated_by_uid'], ['user.uid'],
                                            name='fk_reflex_decision_execution_updated_by'),
                    sa.PrimaryKeyConstraint('uid'),
                    sa.UniqueConstraint('sample_uid', 'reflex_decision_uid',
                                        name='uq_reflex_decision_execution_sample_decision')
                    )
    op.create_index(op.f('ix_reflex_decision_execution_reflex_decision_uid'), 'reflex_decision_execution',
                    ['reflex_decision_uid'], unique=False)
    op.create_index(op.f('ix_reflex_decision_execution_sample_uid'), 'reflex_decision_execution', ['sample_uid'],
                    unique=False)
    op.create_index(op.f('ix_reflex_decision_execution_uid'), 'reflex_decision_execution', ['uid'], unique=False)
    op.create_table('reflex_rule_criteria',
                    sa.Column('reflex_rule_group_uid', sa.String(), nullable=False),
                    sa.Column('analysis_uid', sa.String(), nullable=False),
                    sa.Column('operator', sa.String(), nullable=False),
                    sa.Column('value', sa.String(), nullable=False),
                    sa.Column('priority', sa.Integer(), nullable=True),
                    sa.Column('laboratory_uid', sa.String(), nullable=False),
                    sa.Column('uid', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by_uid', sa.String(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_by_uid', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['analysis_uid'], ['analysis.uid'], ),
                    sa.ForeignKeyConstraint(['created_by_uid'], ['user.uid'],
                                            name='fk_reflex_rule_criteria_created_by'),
                    sa.ForeignKeyConstraint(['laboratory_uid'], ['laboratory.uid'],
                                            name='fk_reflex_rule_criteria_laboratory'),
                    sa.ForeignKeyConstraint(['reflex_rule_group_uid'], ['reflex_rule_group.uid'], ),
                    sa.ForeignKeyConstraint(['updated_by_uid'], ['user.uid'],
                                            name='fk_reflex_rule_criteria_updated_by'),
                    sa.PrimaryKeyConstraint('uid')
                    )
    op.create_index(op.f('ix_reflex_rule_criteria_laboratory_uid'), 'reflex_rule_criteria', ['laboratory_uid'],
                    unique=False)
    op.create_index(op.f('ix_reflex_rule_criteria_reflex_rule_group_uid'), 'reflex_rule_criteria',
                    ['reflex_rule_group_uid'], unique=False)
    op.create_index(op.f('ix_reflex_rule_criteria_uid'), 'reflex_rule_criteria', ['uid'], unique=False)
    op.add_column('analysis', sa.Column('allow_multiple_results', sa.Boolean(), nullable=True))
    op.alter_column('analysis_request', 'metadata_snapshot',
                    existing_type=postgresql.JSONB(astext_type=sa.Text()),
                    nullable=True,
                    existing_server_default=sa.text("'{}'::jsonb"))
    op.add_column('analysis_result', sa.Column('note', sa.String(), nullable=True))
    op.alter_column('patient', 'metadata_snapshot',
                    existing_type=postgresql.JSONB(astext_type=sa.Text()),
                    nullable=True,
                    existing_server_default=sa.text("'{}'::jsonb"))
    op.add_column('sample', sa.Column('note', sa.String(), nullable=True))
    op.alter_column('sample', 'metadata_snapshot',
                    existing_type=postgresql.JSONB(astext_type=sa.Text()),
                    nullable=True,
                    existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('ix_reflex_brain_uid'), table_name='reflex_brain')
    op.drop_index(op.f('ix_reflex_brain_action_uid'), table_name='reflex_brain_action')
    op.drop_index(op.f('ix_reflex_brain_addition_uid'), table_name='reflex_brain_addition')
    op.drop_index(op.f('ix_reflex_action_uid'), table_name='reflex_action')
    op.drop_index(op.f('ix_reflex_brain_final_uid'), table_name='reflex_brain_final')
    op.drop_index(op.f('ix_reflex_brain_condition_criteria_uid'), table_name='reflex_brain_condition_criteria')
    op.drop_index(op.f('ix_reflex_brain_condition_uid'), table_name='reflex_brain_condition')
    op.drop_table('reflex_brain_addition')
    op.drop_table('reflex_brain_final')
    op.drop_table('reflex_brain_action')
    op.drop_table('reflex_brain_condition_criteria')
    op.drop_table('reflex_brain_condition')
    op.drop_table('reflex_action_analysis')
    op.drop_table('reflex_brain')
    op.drop_table('reflex_action')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sample', 'metadata_snapshot',
                    existing_type=postgresql.JSONB(astext_type=sa.Text()),
                    nullable=False,
                    existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_column('sample', 'note')
    op.alter_column('patient', 'metadata_snapshot',
                    existing_type=postgresql.JSONB(astext_type=sa.Text()),
                    nullable=False,
                    existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_column('analysis_result', 'note')
    op.alter_column('analysis_request', 'metadata_snapshot',
                    existing_type=postgresql.JSONB(astext_type=sa.Text()),
                    nullable=False,
                    existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_column('analysis', 'allow_multiple_results')
    op.create_table('reflex_brain_condition',
                    sa.Column('reflex_brain_uid', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('created_by_uid', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('updated_by_uid', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['created_by_uid'], ['user.uid'],
                                            name='reflex_brain_condition_created_by_uid_fkey'),
                    sa.ForeignKeyConstraint(['reflex_brain_uid'], ['reflex_brain.uid'],
                                            name='reflex_brain_condition_reflex_brain_uid_fkey'),
                    sa.ForeignKeyConstraint(['updated_by_uid'], ['user.uid'],
                                            name='reflex_brain_condition_updated_by_uid_fkey'),
                    sa.PrimaryKeyConstraint('uid', name='reflex_brain_condition_pkey'),
                    postgresql_ignore_search_path=False
                    )
    op.create_index(op.f('ix_reflex_brain_condition_uid'), 'reflex_brain_condition', ['uid'], unique=False)
    op.create_table('reflex_brain_condition_criteria',
                    sa.Column('analysis_uid', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('reflex_brain_condition_uid', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('operator', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('created_by_uid', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('updated_by_uid', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['analysis_uid'], ['analysis.uid'],
                                            name=op.f('reflex_brain_condition_criteria_analysis_uid_fkey')),
                    sa.ForeignKeyConstraint(['created_by_uid'], ['user.uid'],
                                            name=op.f('reflex_brain_condition_criteria_created_by_uid_fkey')),
                    sa.ForeignKeyConstraint(['reflex_brain_condition_uid'], ['reflex_brain_condition.uid'], name=op.f(
                        'reflex_brain_condition_criteria_reflex_brain_condition_uid_fkey')),
                    sa.ForeignKeyConstraint(['updated_by_uid'], ['user.uid'],
                                            name=op.f('reflex_brain_condition_criteria_updated_by_uid_fkey')),
                    sa.PrimaryKeyConstraint('analysis_uid', 'reflex_brain_condition_uid', 'uid',
                                            name=op.f('reflex_brain_condition_criteria_pkey'))
                    )
    op.create_index(op.f('ix_reflex_brain_condition_criteria_uid'), 'reflex_brain_condition_criteria', ['uid'],
                    unique=False)
    op.create_table('reflex_brain_final',
                    sa.Column('analysis_uid', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('reflex_brain_action_uid', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('created_by_uid', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('updated_by_uid', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['analysis_uid'], ['analysis.uid'],
                                            name=op.f('reflex_brain_final_analysis_uid_fkey')),
                    sa.ForeignKeyConstraint(['created_by_uid'], ['user.uid'],
                                            name=op.f('reflex_brain_final_created_by_uid_fkey')),
                    sa.ForeignKeyConstraint(['reflex_brain_action_uid'], ['reflex_brain_action.uid'],
                                            name=op.f('reflex_brain_final_reflex_brain_action_uid_fkey')),
                    sa.ForeignKeyConstraint(['updated_by_uid'], ['user.uid'],
                                            name=op.f('reflex_brain_final_updated_by_uid_fkey'))
                    )
    op.create_index(op.f('ix_reflex_brain_final_uid'), 'reflex_brain_final', ['uid'], unique=False)
    op.create_table('reflex_action',
                    sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('sample_type_uid', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('reflex_rule_uid', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('created_by_uid', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('updated_by_uid', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['created_by_uid'], ['user.uid'], name='reflex_action_created_by_uid_fkey'),
                    sa.ForeignKeyConstraint(['reflex_rule_uid'], ['reflex_rule.uid'],
                                            name='reflex_action_reflex_rule_uid_fkey'),
                    sa.ForeignKeyConstraint(['sample_type_uid'], ['sample_type.uid'],
                                            name='reflex_action_sample_type_uid_fkey'),
                    sa.ForeignKeyConstraint(['updated_by_uid'], ['user.uid'], name='reflex_action_updated_by_uid_fkey'),
                    sa.PrimaryKeyConstraint('uid', name='reflex_action_pkey'),
                    postgresql_ignore_search_path=False
                    )
    op.create_index(op.f('ix_reflex_action_uid'), 'reflex_action', ['uid'], unique=False)
    op.create_table('reflex_action_analysis',
                    sa.Column('analysis_uid', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('reflex_action_uid', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['analysis_uid'], ['analysis.uid'],
                                            name=op.f('reflex_action_analysis_analysis_uid_fkey')),
                    sa.ForeignKeyConstraint(['reflex_action_uid'], ['reflex_action.uid'],
                                            name=op.f('reflex_action_analysis_reflex_action_uid_fkey')),
                    sa.PrimaryKeyConstraint('analysis_uid', 'reflex_action_uid',
                                            name=op.f('reflex_action_analysis_pkey'))
                    )
    op.create_table('reflex_brain_addition',
                    sa.Column('analysis_uid', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('reflex_brain_action_uid', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('created_by_uid', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('updated_by_uid', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['analysis_uid'], ['analysis.uid'],
                                            name=op.f('reflex_brain_addition_analysis_uid_fkey')),
                    sa.ForeignKeyConstraint(['created_by_uid'], ['user.uid'],
                                            name=op.f('reflex_brain_addition_created_by_uid_fkey')),
                    sa.ForeignKeyConstraint(['reflex_brain_action_uid'], ['reflex_brain_action.uid'],
                                            name=op.f('reflex_brain_addition_reflex_brain_action_uid_fkey')),
                    sa.ForeignKeyConstraint(['updated_by_uid'], ['user.uid'],
                                            name=op.f('reflex_brain_addition_updated_by_uid_fkey'))
                    )
    op.create_index(op.f('ix_reflex_brain_addition_uid'), 'reflex_brain_addition', ['uid'], unique=False)
    op.create_table('reflex_brain_action',
                    sa.Column('reflex_brain_uid', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('created_by_uid', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('updated_by_uid', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['created_by_uid'], ['user.uid'],
                                            name=op.f('reflex_brain_action_created_by_uid_fkey')),
                    sa.ForeignKeyConstraint(['reflex_brain_uid'], ['reflex_brain.uid'],
                                            name=op.f('reflex_brain_action_reflex_brain_uid_fkey')),
                    sa.ForeignKeyConstraint(['updated_by_uid'], ['user.uid'],
                                            name=op.f('reflex_brain_action_updated_by_uid_fkey')),
                    sa.PrimaryKeyConstraint('uid', name=op.f('reflex_brain_action_pkey'))
                    )
    op.create_index(op.f('ix_reflex_brain_action_uid'), 'reflex_brain_action', ['uid'], unique=False)
    op.create_table('reflex_brain',
                    sa.Column('reflex_action_uid', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('created_by_uid', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('updated_by_uid', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['created_by_uid'], ['user.uid'],
                                            name=op.f('reflex_brain_created_by_uid_fkey')),
                    sa.ForeignKeyConstraint(['reflex_action_uid'], ['reflex_action.uid'],
                                            name=op.f('reflex_brain_reflex_action_uid_fkey')),
                    sa.ForeignKeyConstraint(['updated_by_uid'], ['user.uid'],
                                            name=op.f('reflex_brain_updated_by_uid_fkey')),
                    sa.PrimaryKeyConstraint('uid', name=op.f('reflex_brain_pkey'))
                    )
    op.create_index(op.f('ix_reflex_brain_uid'), 'reflex_brain', ['uid'], unique=False)
    op.drop_index(op.f('ix_reflex_rule_criteria_uid'), table_name='reflex_rule_criteria')
    op.drop_index(op.f('ix_reflex_rule_criteria_reflex_rule_group_uid'), table_name='reflex_rule_criteria')
    op.drop_index(op.f('ix_reflex_rule_criteria_laboratory_uid'), table_name='reflex_rule_criteria')
    op.drop_table('reflex_rule_criteria')
    op.drop_index(op.f('ix_reflex_decision_execution_uid'), table_name='reflex_decision_execution')
    op.drop_index(op.f('ix_reflex_decision_execution_sample_uid'), table_name='reflex_decision_execution')
    op.drop_index(op.f('ix_reflex_decision_execution_reflex_decision_uid'), table_name='reflex_decision_execution')
    op.drop_table('reflex_decision_execution')
    op.drop_index(op.f('ix_reflex_rule_group_uid'), table_name='reflex_rule_group')
    op.drop_index(op.f('ix_reflex_rule_group_reflex_decision_uid'), table_name='reflex_rule_group')
    op.drop_index(op.f('ix_reflex_rule_group_laboratory_uid'), table_name='reflex_rule_group')
    op.drop_table('reflex_rule_group')
    op.drop_index(op.f('ix_reflex_finalize_analysis_uid'), table_name='reflex_finalize_analysis')
    op.drop_index(op.f('ix_reflex_finalize_analysis_reflex_decision_uid'), table_name='reflex_finalize_analysis')
    op.drop_index(op.f('ix_reflex_finalize_analysis_laboratory_uid'), table_name='reflex_finalize_analysis')
    op.drop_table('reflex_finalize_analysis')
    op.drop_index(op.f('ix_reflex_add_analysis_uid'), table_name='reflex_add_analysis')
    op.drop_index(op.f('ix_reflex_add_analysis_reflex_decision_uid'), table_name='reflex_add_analysis')
    op.drop_index(op.f('ix_reflex_add_analysis_laboratory_uid'), table_name='reflex_add_analysis')
    op.drop_table('reflex_add_analysis')
    op.drop_table('reflex_trigger_analysis')
    op.drop_index(op.f('ix_reflex_decision_uid'), table_name='reflex_decision')
    op.drop_index(op.f('ix_reflex_decision_reflex_trigger_uid'), table_name='reflex_decision')
    op.drop_index(op.f('ix_reflex_decision_laboratory_uid'), table_name='reflex_decision')
    op.drop_table('reflex_decision')
    op.drop_index(op.f('ix_reflex_trigger_uid'), table_name='reflex_trigger')
    op.drop_index(op.f('ix_reflex_trigger_reflex_rule_uid'), table_name='reflex_trigger')
    op.drop_index(op.f('ix_reflex_trigger_laboratory_uid'), table_name='reflex_trigger')
    op.drop_table('reflex_trigger')
    # ### end Alembic commands ###
